title: Dreamsome
desc: 有诗意的讽刺漫画
news: 外出探险，暂停更新至29号
author:
  name: Cheng Yichao
  email: onesuperclark@gmail.com 
permalink: /:title 
pygments: true
paginate: 10
markdown: rdiscount
rdiscount:
  extensions: [strict]
production_url : http://dreamsome.org
img_url: http://7vzp4h.com1.z0.glb.clouddn.com
