title: Dreamsome
desc: 有诗意的讽刺漫画
author:
  name: Cheng Yichao
  email: onesuperclark@gmail.com 
permalink: /:title 
pygments: true
paginate: 10
markdown: rdiscount
rdiscount:
  extensions: [strict]
production_url : http://dreamsome.org
