title: Dreamsome
desc: Cheng Yichao's weblog
author:
  name: Cheng Yichao
  email: onesuperclark@gmail.com 
permalink: /:year/:month/:day/:title 
pygments: true
markdown: rdiscount
rdiscount:
  extensions: [strict]
production_url : http://dreamsome.org
